# LFADS Utilities

See the src.

In [ ]:
gen_ics_prior = LearnableDiagonalGaussian(
            batch_size=graph_batch_size,
            z_size = [1, hps['ic_dim']],
            name='gen_ics_prior',
            var = hps['ic_prior_var'],
            trainable_mean=True,
            trainable_var=False)
kl_cost_g0_b = KLCost_GaussianGaussian(gen_ics_posterior, gen_ics_prior).kl_cost_b


In [64]:
test_GRUClipCell()



Model: "GRUClip"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 246, 36)]         0         
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               127488    
Total params: 127,488
Trainable params: 127,488
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[-0.23070076  0.2536174   0.09853305 ... -0.08522673 -0.20194843
   0.2024224 ]
 [-0.25721148  0.339842    0.0416486  ... -0.18940908 -0.30409572
   0.03010286]
 [-0.23013729  0.38037577  0.09360252 ... -0.049852   -0.18864658
   0.1707485 ]
 ...
 [-0.24810478  0.25258836  0.21201608 ... -0.10185561 -0.23760056
   0.24850681]
 [-0.23509276  0.2597233   0.15127341 ... -0.1369887  -0.30795547
   0.06462491]
 [-0.3083426   0.3344782   0.22309446 ... -0.20601623 -0.340707
   0.17592245]], shape=(16, 25

In [70]:
test_GRUClipLayer()


Model: "GRUClip"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 246, 36)]         0         
_________________________________________________________________
gru_clip (GRUClip)           (None, 128)               63360     
Total params: 63,360
Trainable params: 63,360
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[-0.145829   -0.0738971  -0.10125014 ... -0.3566203  -0.28160632
   0.12751628]
 [-0.1078586  -0.03819858 -0.0784252  ... -0.30388248 -0.26838285
   0.13112734]
 [-0.20403881 -0.04190751 -0.10297713 ... -0.1784311  -0.29298502
   0.19574839]
 ...
 [-0.17381434 -0.02557798 -0.15238568 ... -0.38625315 -0.29328454
   0.21715674]
 [-0.10311585 -0.09402761  0.00203776 ... -0.11177816 -0.27137804
   0.18426083]
 [-0.26278093  0.04026812 -0.09496458 ... -0.3568564  -0.2787963
   0.22160673]], shape=(16, 128

In [72]:
test_GRUClipLayer_in_Bidirectional()

Model: "GRUClipBi"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 246, 36)]         0         
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               126720    
Total params: 126,720
Trainable params: 126,720
Non-trainable params: 0
_________________________________________________________________
tf.Tensor(
[[ 0.05232625  0.20494887 -0.12492953 ...  0.11413126  0.25303578
  -0.31101322]
 [ 0.03256029  0.2671073  -0.00039157 ...  0.11336662  0.3193527
  -0.30593503]
 [ 0.01949142  0.3231842  -0.01736745 ...  0.15450042  0.17337021
  -0.21200603]
 ...
 [-0.06974471  0.27610314 -0.08454704 ...  0.16733271  0.25611082
  -0.2095642 ]
 [ 0.10193326  0.17880175 -0.04680509 ...  0.20970306  0.13739228
  -0.22986582]
 [ 0.07257779  0.1905019  -0.08863862 ...  0.12622494  0.16717374
  -0.27231687]], shape=(16,